### ISSUE TITLE
Z axis always reading 9.8m/s2

### ISSUE THREAD

**Issue by incomingflyingbrick** [Joseph82/RxSensors#2]
Hi, I used this library to read the acceleration data I think the library is great.
Is there any way to read 0g instead of 1g of Z axis, when the phone is lying flat on the table?

**Comment by Joseph82** [comment]
Hi! On the z-axis, when the phone is lying flat, the value to expect is indeed 1g. 

You can add extra filter steps in the RxJava chain (where you subtract 9.8m/s²). However, I would discourage it, cause when it is flat you will get 0, but when the z-axis is, for example, perpendicular to the gravity force, then you are gonna get -9.8m/s²

**Comment by incomingflyingbrick** [comment]
I will, I will rethink the design of my program. Thank you for the quick response!

**Comment by Joseph82** [comment]
No problem! If you have more questions you are welcome to ask.
